
version: "3.8"
services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
       - ./public:/var/www/html
    depends_on:
      - php-fpm  
    networks:
      - app-network
   
  php-fpm:
    # image: php:fpm  # Specify the PHP-FPM version
    # container_name: php-fpm
    # volumes:
    #   - ./public:/var/www/html
    build:
      context: ./
      dockerfile: Dockerfile  # Reference the Dockerfile here
    container_name: php-fpm
    volumes:
      - ./public:/var/www/html
    depends_on:
      - mariadb  
    networks:
      - app-network
  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - ./public:/var/www/html  # Mount your PHP project
    networks:
      - app-network
    depends_on:
      - php-fpm
    command: ["composer", "install"]  # Run Composer install command

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: user
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: ""
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge      


# version: "3.8"

# services:
#   webserver:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ./public:/var/www/html
#     depends_on:
#       - php-fpm
#     networks:
#       - app-network

#   php-fpm:
#     image: php:8.1-fpm
#     container_name: php-fpm
#     volumes:
#       - ./public:/var/www/html
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge
